# Configure this Discovery Server
eureka:
  client: 
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0  

# HTTP (Tomcat) port
server:
  port: 8761   

  
